---
detectors:
  DuplicateMethodCall:
    max_calls: 4

  RepeatedConditional:
    max_ifs: 4

  UncommunicativeModuleName:
    enabled: false

  IrresponsibleModule:
    enabled: false

  FeatureEnvy:
    enabled: false

  UtilityFunction:
    enabled: false

  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    max_statements: 8

  NilCheck:
    enabled: false
